#!/usr/bin/env python3
"""
Revision Summary Visualizations

Generate Bokeh plots for polygon revision tracking across all demo stations.
Aggregates comparison metrics from station _versions.json files.
"""

import json
import sqlite3
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from datetime import datetime
import geopandas as gpd
from shapely.geometry import Point
import sys

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.config.paths import HYDAT_DB_PATH, HYDAT_REVISION_METRICS_CSV
from scripts.demo_setup.setup_utilities import query_hydat_version

from bokeh.plotting import figure
from bokeh.layouts import column
from bokeh.models import (
    HoverTool, ColumnDataSource, DataTable,
    TableColumn, NumberFormatter, HTMLTemplateFormatter,
    TapTool, OpenURL, Legend, LegendItem, CDSView, GroupFilter,
    InlineStyleSheet
)
from bokeh.palettes import RdYlGn11

# Project paths
BASE_DIR = Path(__file__).resolve().parent.parent.parent
STATIONS_DIR = BASE_DIR / "book_docs" / "stations"
STATION_PAGES_DIR = BASE_DIR / "book_docs" / "station_pages" / "stations"
TUFTE_TABLE_CSS_PATH = BASE_DIR / "book_docs" / "_static" / "tufte_table.css"

# Define high-contrast colors for each category
category_colors = {
    '0-2%': "#018a33",      # Green
    '2-5%': '#a3e635',      # Light green/yellow
    '5-10%': '#fbbf24',     # Yellow/orange
    '10-20%': '#f97316',    # Orange
    '20%+': '#dc2626'       # Red
}

# Load Tufte-style CSS for DataTables
def load_tufte_table_css():
    """Load Tufte table CSS from static folder."""
    if TUFTE_TABLE_CSS_PATH.exists():
        return TUFTE_TABLE_CSS_PATH.read_text()
    return ""

TUFTE_TABLE_CSS = load_tufte_table_css()

# Define colors for data backlog categories (green=current, red=old)
backlog_colors = {
    '<1 year': '#228833',      # Green - Current
    '1-2 years': '#a3e635',    # Light green - Recent
    '2-5 years': '#fbbf24',    # Yellow - Moderate backlog
    '5-10 years': '#f97316',   # Orange - Significant backlog
    '10+ years': '#dc2626'     # Red - Critical backlog
}

def categorize_polygon_change(pct):
    abs_pct = abs(pct)
    if abs_pct < 2:
        return '0-2%'
    elif abs_pct < 5:
        return '2-5%'
    elif abs_pct < 10:
        return '5-10%'
    elif abs_pct < 20:
        return '10-20%'
    else:
        return '20%+'


def categorize_jsi(jsi: float) -> str:
    """Categorize Jaccard Similarity Index into agreement levels."""
    if jsi >= 0.95:
        return 'Excellent (≥0.95)'
    elif jsi >= 0.90:
        return 'Good (0.90-0.95)'
    elif jsi >= 0.80:
        return 'Moderate (0.80-0.90)'
    elif jsi >= 0.70:
        return 'Poor (0.70-0.80)'
    else:
        return 'Very Poor (<0.70)'


# Color scheme for JSI: green for high JSI (good agreement), red for low JSI (poor agreement)
jsi_colors = {
    'Excellent (≥0.95)': '#018a33',     # Green
    'Good (0.90-0.95)': '#a3e635',      # Light green
    'Moderate (0.80-0.90)': '#fbbf24',  # Yellow
    'Poor (0.70-0.80)': '#f97316',      # Orange
    'Very Poor (<0.70)': '#dc2626'      # Red
}


def categorize_backlog_duration(days):
    """Categorize time since last data record.

    Args:
        days: Number of days since last data record

    Returns:
        Category string describing backlog duration
    """
    if days < 365:  # < 1 year
        return '<1 year'
    elif days < 730:  # 1-2 years
        return '1-2 years'
    elif days < 1825:  # 2-5 years
        return '2-5 years'
    elif days < 3650:  # 5-10 years
        return '5-10 years'
    else:
        return '10+ years'


def load_revision_metrics(include_coordinates: bool = True) -> pd.DataFrame:
    """Load polygon revision comparison metrics from centralized CSV.

    This CSV is generated by integrate_hydat_polygons.py and contains comparison
    metrics for all stations where polygon revisions have been integrated.

    Args:
        include_coordinates: If True (default), includes lat/lon columns from CSV.
                           Parameter kept for API consistency with load_caravan_comparison_data().

    Returns:
        DataFrame with columns: station_id, comparison_key, old_version, new_version,
        jaccard_index, percent_area_diff, absolute_area_diff_km2, old_area_km2,
        new_area_km2, latitude, longitude, timestamp, data_source

    Raises:
        FileNotFoundError: If CSV doesn't exist with instructions to generate it
    """
    if not HYDAT_REVISION_METRICS_CSV.exists():
        raise FileNotFoundError(
            f"Revision metrics CSV not found at {HYDAT_REVISION_METRICS_CSV}.\\n"
            "Run 'python scripts/demo_setup/integrate_hydat_polygons.py' to generate it."
        )

    df = pd.read_csv(HYDAT_REVISION_METRICS_CSV)

    if not include_coordinates:
        df = df.drop(columns=['latitude', 'longitude'], errors='ignore')

    return df


def _fetch_station_coordinates(station_ids: List[str]) -> pd.DataFrame:
    """Fetch latitude/longitude for the provided station IDs from HYDAT."""
    if not station_ids or not HYDAT_DB_PATH.exists():
        return pd.DataFrame()

    placeholders = ",".join(["?"] * len(station_ids))
    query = (
        "SELECT STATION_NUMBER, LATITUDE, LONGITUDE FROM STATIONS "
        f"WHERE STATION_NUMBER IN ({placeholders})"
    )

    conn = sqlite3.connect(HYDAT_DB_PATH)
    try:
        coords = pd.read_sql_query(query, conn, params=station_ids)
    finally:
        conn.close()

    return coords.rename(columns={
        'STATION_NUMBER': 'station_id',
        'LATITUDE': 'latitude',
        'LONGITUDE': 'longitude'
    })


def _station_page_url(station_id: str) -> str:
    """Return relative station page link when HTML exists, else empty string."""
    html_path = STATION_PAGES_DIR / f"{station_id}.html"
    if html_path.exists():
        return f"../station_pages/stations/{station_id}.html"
    return ""


def _prepare_caravan_plot_dataframe() -> pd.DataFrame:
    """Prepare Caravan comparison data with geometry-derived plot columns."""
    df = load_caravan_comparison_data(include_coordinates=True)
    if df.empty:
        return df

    df = df.dropna(subset=['latitude', 'longitude']).copy()
    if df.empty:
        return df

    gdf = gpd.GeoDataFrame(df,
                           geometry=gpd.points_from_xy(df.longitude, df.latitude),
                           crs="EPSG:4326")
    gdf = gdf.to_crs(epsg=3857)

    df['x'] = gdf.geometry.x
    df['y'] = gdf.geometry.y
    df['category'] = df['percent_area_diff'].apply(categorize_polygon_change)
    df['color'] = df['category'].map(category_colors)
    df['url'] = df['station_id'].apply(_station_page_url)
    df['map_url'] = df['url'].apply(lambda val: val if val else '#')
    df['abs_percent_area_diff'] = df['percent_area_diff'].abs()
    df['abs_percent_area_diff_log'] = df['abs_percent_area_diff'].clip(lower=1e-3)

    return df


def _build_caravan_map(df: pd.DataFrame, source: ColumnDataSource):
    """Create Caravan comparison map sharing a ColumnDataSource."""
    p = figure(
        title="",
        x_axis_type="mercator",
        y_axis_type="mercator",
        width=800,
        height=600,
        tools="pan,wheel_zoom,lasso_select,box_select,reset,save",
        toolbar_location="above",
        match_aspect=True, # keep aspect ratio
    )
    p.add_tile("CartoDB Positron", retina=True)

    renderers = []
    for cat in ['0-2%', '2-5%', '5-10%', '10-20%', '20%+']:
        if cat not in df['category'].values:
            continue
        view = CDSView(filter=GroupFilter(column_name='category', group=cat))
        circles = p.scatter(
            'x', 'y',
            source=source,
            view=view,
            size=12,
            color=category_colors[cat],
            line_color='black',
            line_width=1,
            alpha=0.8,
            selection_color=category_colors[cat],
            nonselection_alpha=0.2,
            legend_label=cat
        )
        renderers.append(circles)

    hover = HoverTool(
        renderers=renderers,
        tooltips=[
            ("Station", "@station_id"),
            ("Jaccard Index", "@jaccard_index{0.00}"),
            ("Percent Area Change", "@percent_area_diff{0.0}%"),
            ("Category", "@category"),
            ("", "Click to view station page")
        ]
    )
    p.add_tools(hover)

    tap = TapTool()
    p.add_tools(tap)
    taptool = p.select(type=TapTool)
    taptool.callback = OpenURL(url='@map_url')

    p.legend.location = "top_right"
    p.legend.title = "Area Change"
    p.legend.title_text_font_style = "bold"
    p.legend.click_policy = "hide"

    return p


def _build_caravan_cdf(source: ColumnDataSource, metric: str):
    """Create CDF plot linked to the shared ColumnDataSource."""
    if metric == 'area':
        title = "Cumulative Distribution of Absolute Percent Area Changes"
        x_axis_label = "Absolute Percent Area Change (%)"
        x_axis_type = 'log'
        tooltip_label = "|ΔArea|"
        tooltip_field = '@abs_percent_area_diff{0.0}%'
    else:
        title = "Cumulative Distribution of Jaccard Similarity Indices"
        x_axis_label = "Jaccard Similarity Index"
        x_axis_type = 'linear'
        tooltip_label = "Jaccard Index"
        tooltip_field = '@jaccard_index{0.000}'

    p = figure(
        title=title,
        x_axis_label=x_axis_label,
        y_axis_label="Cumulative Probability",
        width=800,
        height=300,
        tools="pan,box_select,lasso_select,wheel_zoom,reset,save",
        toolbar_location="right",
        x_axis_type=x_axis_type
    )

    cdf_line = p.line('cdf_x', 'cdf_y', source=source, line_width=2, color='gray', alpha=0.6)
    cdf_points = p.scatter('cdf_x', 'cdf_y', source=source, size=6, color='color', alpha=0.8)

    hover = HoverTool(renderers=[cdf_points], tooltips=[
        ("Station", "@station_id"),
        (tooltip_label, tooltip_field)
    ])
    p.add_tools(hover)

    p.y_range.start = -0.01
    p.y_range.end = 1.01

    return p


def plot_caravan_map_with_cdf(metric: str = 'jaccard'):
    """Generate linked Caravan comparison map and CDF plots."""
    metric = metric.lower()
    df = _prepare_caravan_plot_dataframe()
    if df.empty:
        from bokeh.models import Div
        return Div(text="<p>No comparison data available.</p>")

    if metric == 'area':
        sort_col = 'abs_percent_area_diff'
        df_sorted = df.sort_values(sort_col).reset_index(drop=True)
        df_sorted['cdf_x'] = df_sorted['abs_percent_area_diff_log']
    else:
        sort_col = 'jaccard_index'
        df_sorted = df.sort_values(sort_col).reset_index(drop=True)
        df_sorted['cdf_x'] = df_sorted['jaccard_index']
        metric = 'jaccard'

    df_sorted['cdf_y'] = (np.arange(len(df_sorted)) + 1) / len(df_sorted)

    source = ColumnDataSource(df_sorted)

    map_plot = _build_caravan_map(df_sorted, source)
    cdf_plot = _build_caravan_cdf(source, metric)

    return column(map_plot, cdf_plot)


def load_caravan_comparison_data(include_coordinates: bool = True) -> pd.DataFrame:
    """Load Caravan vs. WSC comparison data and optionally add coordinates."""
    csv_path = BASE_DIR / "book_docs/data/polygon_comparisons/caravan_vs_wsc2024/comparison_metrics.csv"

    if not csv_path.exists():
        # Return empty DataFrame with expected column structure
        return pd.DataFrame(columns=[
            'station_id', 'jaccard_index', 'percent_area_diff',
            'absolute_area_diff_km2', 'old_area_km2', 'new_area_km2'
        ])

    df = pd.read_csv(csv_path)

    if df.empty or not include_coordinates:
        return df

    has_latlon = {'latitude', 'longitude'}.issubset(df.columns)
    if has_latlon and df[['latitude', 'longitude']].notna().any().all():
        return df

    station_ids = sorted(df['station_id'].astype(str).unique())
    coords = _fetch_station_coordinates(station_ids)
    if coords.empty:
        return df

    merged = df.merge(coords, on='station_id', how='left')
    return merged


def summarize_caravan_comparison(df: Optional[pd.DataFrame] = None):
    """Compute headline statistics for the Caravan comparison dataset and return DataFrame.

    Args:
        df: Optional DataFrame with comparison data

    Returns:
        DataFrame with Metric and Value columns
    """
    if df is None:
        df = load_caravan_comparison_data(include_coordinates=False)

    if df is None or df.empty:
        return pd.DataFrame()

    # Create summary as a vertical table (Metric, Value)
    rows = [
        ('Stations compared', str(int(len(df)))),
        ('Area change > 10%', f"{(df['percent_area_diff'].abs() > 10).mean() * 100:.1f}%"),
        ('JSI < 0.80', f"{(df['jaccard_index'] < 0.8).mean() * 100:.1f}%"),
        ('Median Jaccard index', f"{df['jaccard_index'].median():.3f}"),
        ('Median |Δarea| (%)', f"{df['percent_area_diff'].abs().median():.2f}%"),
        ('Median |Δarea| (km²)', f"{df['absolute_area_diff_km2'].median():.2f}"),
        ('Largest |Δarea| (km²)', f"{df['absolute_area_diff_km2'].max():.1f}")
    ]

    summary_df = pd.DataFrame(rows, columns=['Metric', 'Value'])
    return summary_df


def generate_caravan_summary_table():
    """Generate Bokeh DataTable widget with summary metrics for Caravan comparison.

    Returns:
        Bokeh DataTable widget displaying key comparison statistics
    """
    summary_df = summarize_caravan_comparison()

    if summary_df.empty:
        from bokeh.models import Div
        return Div(text="<p>No comparison data available.</p>")

    source = ColumnDataSource(summary_df)

    columns = [
        TableColumn(field="Metric", title="Metric", width=250),
        TableColumn(field="Value", title="Value", width=200),
    ]

    data_table = DataTable(
        source=source,
        columns=columns,
        width=460,
        height=230,
        index_position=None,
        sortable=False,
        reorderable=False,
        stylesheets=[InlineStyleSheet(css=TUFTE_TABLE_CSS)]
    )

    return data_table


def load_caravan_summary_table(df: Optional[pd.DataFrame] = None) -> pd.DataFrame:
    """Return a formatted summary table for the Caravan comparison."""
    summary = summarize_caravan_comparison(df)
    if not summary:
        return pd.DataFrame(columns=["Metric", "Value"])

    rows = [
        ("Stations compared", f"{summary['n_stations']:,}"),
        ("Area change > 10%", f"{summary['pct_area_diff_gt_10']:.1f}%"),
        ("JSI < 0.80", f"{summary['pct_jsi_lt_80']:.1f}%"),
        ("Median Jaccard index", f"{summary['median_jsi']:.3f}"),
        ("Median |Δarea| (%)", f"{summary['median_area_diff_pct']:.2f}%"),
        ("Median |Δarea| (km²)", f"{summary['median_abs_area_km2']:.2f}"),
        ("Largest |Δarea| (km²)", f"{summary['largest_area_increase_km2']:.1f}")
    ]

    return pd.DataFrame(rows, columns=["Metric", "Value"])


def load_caravan_summary_table_html(df: Optional[pd.DataFrame] = None) -> str:
    """Return formatted summary table as HTML string for Jupyter Book rendering."""
    table = load_caravan_summary_table(df)
    if table.empty:
        return "<p><em>Comparison metrics are unavailable. Run <code>python scripts/generation/compare_caravan_polygons.py</code> first.</em></p>"

    return table.to_html(index=False, border=0, classes="cf-summary-table")


def plot_revision_map(data: pd.DataFrame = None):
    """Generate interactive map showing station locations colored by area change.

    Args:
        data: Optional DataFrame with comparison metrics. If None, loads
              data from centralized CSV.

    Returns:
        Bokeh figure with tile provider background and colored markers
    """
    if data is None:
        data = load_revision_metrics()

    df = data

    if df.empty:
        from bokeh.models import Div
        return Div(text="<p>No comparison data available.</p>")

    # Remove stations without coordinates
    df = df.dropna(subset=['latitude', 'longitude'])

    if df.empty:
        from bokeh.models import Div
        return Div(text="<p>No stations with valid coordinates.</p>")

    gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.longitude, df.latitude), crs="EPSG:4326")
    gdf = gdf.to_crs(epsg=3857)  # Web Mercator for plotting

    # Convert lat/lon to Web Mercator for tile overlay
    df['x'] = gdf.geometry.x
    df['y'] = gdf.geometry.y

    # Categorize percent area differences into 5 bins

    df['category'] = df['percent_area_diff'].apply(categorize_polygon_change)
    df['color'] = df['category'].map(category_colors)

    # Create figure with tile provider
    p = figure(
        title="",
        x_axis_type="mercator",
        y_axis_type="mercator",
        width=800,
        height=600,
        tools="pan,wheel_zoom,lasso_select,box_select,reset,save",
        toolbar_location="above",
        match_aspect=True, # keep aspect ratio
    )
    p.add_tile("CartoDB Positron", retina=True)

    df['url'] = df['station_id'].apply(lambda sid: f"../station_pages/stations/{sid}.html")

    # Create per-category renderers for interactive legend
    legend_items = []
    renderers = []

    for cat in ['0-2%', '2-5%', '5-10%', '10-20%', '20%+']:
        cat_df = df[df['category'] == cat]
        if not cat_df.empty:
            cat_source = ColumnDataSource(cat_df)
            renderer = p.scatter(
                'x', 'y',
                source=cat_source,
                size=12,
                color=category_colors[cat],
                line_color='black',
                line_width=1,
                alpha=0.8,
                legend_label=cat
            )
            renderers.append(renderer)
            legend_items.append(LegendItem(label=cat, renderers=[renderer]))

    # Add hover tool (works on all renderers)
    hover = HoverTool(
        tooltips=[
            ("Station", "@station_id"),
            ("Jaccard Index", "@jaccard_index{0.00}"),
            ("Percent Area Change", "@percent_area_diff{0.0}%"),
            ("Category", "@category"),
            ("", "Click to view station page")
        ]
    )
    p.add_tools(hover)

    # Add tap tool for clickable links to station pages
    tap = TapTool()
    p.add_tools(tap)
    taptool = p.select(type=TapTool)
    taptool.callback = OpenURL(url="@url")

    # Configure legend
    p.legend.location = "top_right"
    p.legend.title = "Area Change"
    p.legend.title_text_font_style = "bold"
    p.legend.click_policy = "hide"

    return p


def plot_jaccard_cdf(data: pd.DataFrame = None):
    """Generate CDF plot for Jaccard similarity indices.

    Args:
        data: Optional DataFrame with comparison metrics. If None, loads
              data from centralized CSV.

    Returns:
        Bokeh figure with CDF line and percentile annotations
    """
    if data is None:
        data = load_revision_metrics()

    df = data
    df = df[df['jaccard_index'].notnull()]

    if df.empty:
        from bokeh.models import Div
        return Div(text="<p>No comparison data available.</p>")

    # Calculate CDF
    sorted_values = np.sort(df['jaccard_index'].values)
    yvals = np.arange(1, len(sorted_values) + 1) / len(sorted_values)

    # Create figure
    p = figure(
        title="Cumulative Distribution of Jaccard Similarity Indices",
        x_axis_label="Jaccard Similarity Index",
        y_axis_label="Cumulative Probability",
        width=700,
        height=400,
        tools="pan,wheel_zoom,lasso_select,box_select,reset,save",
        toolbar_location="right",
    )
    assert len(sorted_values) == len(yvals), f'Length mismatch: {len(sorted_values)} vs {len(yvals)}'

    # Plot CDF
    p.line(sorted_values, yvals, line_width=2, color='navy', legend_label='JSI CDF')
    p.scatter(sorted_values, yvals, size=4, color='navy', alpha=0.6)

    # Add percentile annotations
    percentiles = [25, 50, 75]
    for pct in percentiles:
        value = np.percentile(sorted_values, pct)
        p.line([value, value], [0.01, pct/100], line_dash='dashed',
               line_width=1, color='gray', alpha=0.5)
        p.line([sorted_values.min(), value], [pct/100, pct/100],
               line_dash='dashed', line_width=1, color='gray', alpha=0.5)

    # Styling
    p.legend.location = "top_left"
    p.y_range.start = 0
    p.y_range.end = 1

    return p


def plot_area_change_cdf(data: pd.DataFrame = None):
    """Generate CDF plot for percent area differences.

    Args:
        data: Optional DataFrame with comparison metrics. If None, loads
              data from centralized CSV.

    Returns:
        Bokeh figure with CDF line and reference lines
    """
    if data is None:
        data = load_revision_metrics()

    df = data

    if df.empty:
        from bokeh.models import Div
        return Div(text="<p>No comparison data available. Run polygon integration first.</p>")

    # Calculate CDF using absolute percent change
    sorted_values = np.sort(np.abs(df['percent_area_diff'].values)) + 0.001
    yvals = np.arange(1, len(sorted_values) + 1) / len(sorted_values)

    # Create figure
    p = figure(
        title="Cumulative Distribution of Absolute Percent Area Changes",
        x_axis_label="Absolute Percent Area Change (%)",
        y_axis_label="Cumulative Probability",
        width=700,
        height=400,
        tools="pan,wheel_zoom,lasso_select,box_select,reset,save",
        x_axis_type='log'
    )

    # Plot CDF
    p.line(sorted_values, yvals, line_width=2, color='darkred',
           legend_label='|ΔArea| CDF')
    p.scatter(sorted_values, yvals, size=4, color='darkred', alpha=0.6)

    # Add percentile annotations
    percentiles = [50, 75, 90]
    for pct in percentiles:
        value = np.percentile(sorted_values, pct)
        p.line([value, value], [0, pct/100], line_dash='dashed',
               line_width=1, color='gray', alpha=0.5)

    # Styling
    p.legend.location = "bottom_right"
    p.x_range.start = 0.9e-4
    p.y_range.start = 0
    p.y_range.end = 1

    return p


def generate_revision_table():
    """Generate sortable DataTable with all comparison metrics.

    Returns:
        Bokeh DataTable layout
    """
    df = load_revision_metrics()

    if df.empty:
        from bokeh.models import Div
        return Div(text="<p>No comparison data available.</p>")

    # Sort by station ID
    df = df.sort_values('station_id')

    # Select and rename columns for display
    display_df = df[[
        'station_id', 'jaccard_index', 'percent_area_diff',
        'old_area_km2', 'new_area_km2', 'absolute_area_diff_km2'
    ]].copy()

    # Add station page link for "Go to Page" column
    display_df['page_link'] = display_df['station_id'].copy()

    # Create ColumnDataSource
    source = ColumnDataSource(display_df)

    # Define columns with formatting
    columns = [
        TableColumn(field="station_id", title="Station ID", width=100),
        TableColumn(field="jaccard_index", title="Jaccard Index",
                   formatter=NumberFormatter(format="0.0000"), width=120),
        TableColumn(field="percent_area_diff", title="Area Change (%)",
                   formatter=NumberFormatter(format="0.00"), width=130),
        TableColumn(field="old_area_km2", title="Old Area (km²)",
                   formatter=NumberFormatter(format="0.0"), width=120),
        TableColumn(field="new_area_km2", title="New Area (km²)",
                   formatter=NumberFormatter(format="0.0"), width=120),
        TableColumn(field="absolute_area_diff_km2", title="|ΔArea| (km²)",
                   formatter=NumberFormatter(format="0.00"), width=120),
        TableColumn(field="page_link", title="Go to Page",
                   formatter=HTMLTemplateFormatter(
                       template='<a href="../station_pages/stations/<%= value %>.html" target="_blank" class="cf-link">View →</a>'
                   ), width=100),
    ]

    # Create DataTable
    data_table = DataTable(
        source=source,
        columns=columns,
        width=800,
        height=400,
        sortable=True,
        reorderable=True,
        index_position=None,
        stylesheets=[InlineStyleSheet(css=TUFTE_TABLE_CSS)]
    )

    return data_table


def generate_caravan_comparison_table():
    """Generate sortable DataTable for Caravan vs. WSC comparison metrics."""
    df = load_caravan_comparison_data(include_coordinates=False)

    if df.empty:
        from bokeh.models import Div
        return Div(text="<p>No comparison data available.</p>")

    df = df.sort_values('station_id')

    display_df = df[[
        'station_id', 'jaccard_index', 'percent_area_diff',
        'old_area_km2', 'new_area_km2', 'absolute_area_diff_km2'
    ]].copy()

    display_df['page_url'] = display_df['station_id'].apply(_station_page_url)

    source = ColumnDataSource(display_df)

    link_template = (
        "<% if (value) { %>"
        '<a href="<%= value %>" target="_blank" class="cf-link">View →</a>'
        "<% } else { %>—<% } %>"
    )

    columns = [
        TableColumn(field="station_id", title="Station ID", width=100),
        TableColumn(field="jaccard_index", title="Jaccard Index",
                   formatter=NumberFormatter(format="0.0000"), width=120),
        TableColumn(field="percent_area_diff", title="Area Change (%)",
                   formatter=NumberFormatter(format="0.00"), width=130),
        TableColumn(field="old_area_km2", title="Caravan Area (km²)",
                   formatter=NumberFormatter(format="0.0"), width=150),
        TableColumn(field="new_area_km2", title="WSC Area (km²)",
                   formatter=NumberFormatter(format="0.0"), width=150),
        TableColumn(field="absolute_area_diff_km2", title="|ΔArea| (km²)",
                   formatter=NumberFormatter(format="0.00"), width=140),
        TableColumn(field="page_url", title="Station Page",
                   formatter=HTMLTemplateFormatter(template=link_template), width=140),
    ]

    data_table = DataTable(
        source=source,
        columns=columns,
        width=800,
        height=450,
        sortable=True,
        reorderable=True,
        index_position=None,
        stylesheets=[InlineStyleSheet(css=TUFTE_TABLE_CSS)]
    )

    return data_table


def collect_backlog_data():
    """Collect reporting backlog data for all active HYDAT stations.

    Returns:
        DataFrame with backlog data or None if error/no data
    """
    if not HYDAT_DB_PATH.exists():
        return None

    conn = sqlite3.connect(HYDAT_DB_PATH)

    try:
        # Get HYDAT version date
        version, version_date_str = query_hydat_version(conn)
        if version_date_str is None:
            return None

        # Parse version date
        try:
            version_date = datetime.strptime(version_date_str.split()[0], "%Y-%m-%d")
        except (ValueError, IndexError):
            version_date = datetime.strptime(version_date_str, "%Y-%m-%d")

        # Query active stations with coordinates
        query = """
        SELECT STATION_NUMBER, STATION_NAME, LONGITUDE, LATITUDE, HYD_STATUS
        FROM STATIONS
        WHERE HYD_STATUS = 'A'
          AND LONGITUDE IS NOT NULL
          AND LATITUDE IS NOT NULL
        """
        stations_df = pd.read_sql_query(query, conn)

        if stations_df.empty:
            return None

        # For each station, find most recent flow data
        backlog_data = []
        for _, row in stations_df.iterrows():
            station_id = row['STATION_NUMBER']

            # Query most recent flow data
            flow_query = """
            SELECT MAX(YEAR) as max_year, MAX(MONTH) as max_month
            FROM DLY_FLOWS
            WHERE STATION_NUMBER = ?
            """
            flow_df = pd.read_sql_query(flow_query, conn, params=(station_id,))

            if flow_df.empty or pd.isna(flow_df['max_year'].iloc[0]):
                continue

            max_year = int(flow_df['max_year'].iloc[0])
            max_month = int(flow_df['max_month'].iloc[0])

            # Get last day of month
            day_query = """
            SELECT NO_DAYS
            FROM DLY_FLOWS
            WHERE STATION_NUMBER = ? AND YEAR = ? AND MONTH = ?
            """
            day_df = pd.read_sql_query(day_query, conn, params=(station_id, max_year, max_month))

            if not day_df.empty:
                last_day = int(day_df['NO_DAYS'].iloc[0]) if not pd.isna(day_df['NO_DAYS'].iloc[0]) else 1
                try:
                    most_recent_date = datetime(max_year, max_month, last_day)
                except ValueError:
                    most_recent_date = datetime(max_year, max_month, 1)

                backlog_days = (version_date - most_recent_date).days

                backlog_data.append({
                    'station_id': station_id,
                    'station_name': row['STATION_NAME'],
                    'latitude': row['LATITUDE'],
                    'longitude': row['LONGITUDE'],
                    'last_record_date': most_recent_date.strftime('%Y-%m-%d'),
                    'backlog_days': backlog_days
                })

        conn.close()

        if not backlog_data:
            return None

        # Create DataFrame
        df = pd.DataFrame(backlog_data)
        df = df.dropna(subset=['latitude', 'longitude'])

        if df.empty:
            return None

        # Get set of processed stations (those with station pages)
        processed_stations = {d.name for d in STATIONS_DIR.iterdir() if d.is_dir() and len(d.name) == 7}

        # Add derived columns
        gdf = gpd.GeoDataFrame(
            df,
            geometry=gpd.points_from_xy(df.longitude, df.latitude),
            crs="EPSG:4326"
        )
        gdf = gdf.to_crs(epsg=3857)

        df['x'] = gdf.geometry.x
        df['y'] = gdf.geometry.y
        df['category'] = df['backlog_days'].apply(categorize_backlog_duration)
        df['color'] = df['category'].map(backlog_colors)
        # Set URL to '#' for stations without processed pages, normal link for processed stations
        df['url'] = df['station_id'].apply(
            lambda sid: f"station_pages/stations/{sid}.html" if sid in processed_stations else "#"
        )
        df['backlog_display'] = df['backlog_days'].apply(
            lambda d: f"{d} days ({d/365.25:.1f} years)" if d >= 365 else f"{d} days"
        )
        df['backlog_months'] = df['backlog_days'] / 30.44

        return df

    except Exception as e:
        conn.close()
        return None


def plot_backlog_map(df, shared_source=None):
    """Plot interactive map of station backlog.

    Args:
        df: DataFrame with backlog data (should be pre-sorted for CDF alignment)
        shared_source: Optional shared ColumnDataSource for linked plots

    Returns:
        Bokeh figure
    """
    if shared_source is None:
        shared_source = ColumnDataSource(df)

    # Create figure
    p = figure(
        title="",
        x_axis_type="mercator",
        y_axis_type="mercator",
        width=800,
        height=600,
        tools="pan,wheel_zoom,lasso_select,box_select,reset,save",
        toolbar_location="above",
        match_aspect=True
    )
    p.add_tile("CartoDB Positron", retina=True)

    # Plot each category separately for legend toggle using CDSView
    all_renderers = []
    for cat in ['<1 year', '1-2 years', '2-5 years', '5-10 years', '10+ years']:
        cat_df = df[df['category'] == cat]
        if not cat_df.empty:
            # Create a view that filters the shared source by category
            view = CDSView(filter=GroupFilter(column_name='category', group=cat))
            circles = p.scatter(
                'x', 'y',
                source=shared_source,
                view=view,
                size=12,
                color=backlog_colors[cat],
                line_color='black',
                line_width=1,
                alpha=0.8,
                selection_color=backlog_colors[cat],
                nonselection_alpha=0.2,
                legend_label=cat
            )
            all_renderers.append(circles)

    # Configure legend for toggling
    p.legend.location = "top_left"
    p.legend.title = "Data Backlog"
    p.legend.title_text_font_style = "bold"
    p.legend.click_policy = "hide"

    # Add hover tool for all renderers
    hover = HoverTool(
        renderers=all_renderers,
        tooltips=[
            ("Station", "@station_id"),
            ("Name", "@station_name"),
            ("Last Record", "@last_record_date"),
            ("Backlog", "@backlog_display"),
            ("Category", "@category"),
            ("", "Click to view station page")
        ]
    )
    p.add_tools(hover)

    # Add tap tool for clickable links
    tap = TapTool()
    p.add_tools(tap)
    taptool = p.select(type=TapTool)
    taptool.callback = OpenURL(url="@url")

    return p


def plot_backlog_cdf(df=None, shared_source=None):
    """Generate CDF plot for data reporting backlog in month-equivalents.

    Args:
        df: DataFrame with backlog data (should already be sorted with cdf_y column)
        shared_source: Optional shared ColumnDataSource for linked plots

    Returns:
        Bokeh figure with CDF line and percentile annotations
    """
    # If no data provided, collect it
    if df is None:
        df = collect_backlog_data()
        if df is None:
            from bokeh.models import Div
            return Div(text="<p>No backlog data available.</p>")

    # Assume data is already sorted with cdf_y (done in plot_network_backlog)
    if shared_source is None:
        shared_source = ColumnDataSource(df)

    # Create figure
    p = figure(
        title="Cumulative Distribution of Data Reporting Backlog",
        x_axis_label="Backlog (months)",
        y_axis_label="Cumulative Probability",
        width=800,
        height=250,
        tools="pan,box_select,lasso_select,wheel_zoom,reset,save",
        toolbar_location="right",
        x_axis_type='log'
    )

    # Plot CDF
    cdf_circles = p.scatter(
        'backlog_months', 'cdf_y',
        source=shared_source,
        size=6,
        color='color',
        alpha=0.7,
        selection_color='color',
        selection_alpha=1.0,
        nonselection_alpha=0.2
    )

    # Add connecting line
    p.line(
        'backlog_months', 'cdf_y',
        source=shared_source,
        line_width=2,
        color='grey',
        alpha=0.6
    )

    # Add percentile annotations
    percentiles = [25, 50, 75, 90]
    for pct in percentiles:
        idx = int(len(df) * pct / 100)
        if idx < len(df):
            value = df.iloc[idx]['backlog_months']
            p.line([value, value], [0, pct/100], line_dash='dashed',
                   line_width=1, color='gray', alpha=0.5)

    # Styling
    p.y_range.start = -0.01
    p.y_range.end = 1.01

    # Add hover
    hover_cdf = HoverTool(
        renderers=[cdf_circles],
        tooltips=[
            ("Station", "@station_id"),
            ("Backlog", "@backlog_display"),
            ("Category", "@category"),
        ]
    )
    p.add_tools(hover_cdf)

    return p


def plot_network_backlog():
    """Generate linked map and CDF showing backlog of daily flow data reporting.

    Creates an interactive visualization where selecting points in the CDF highlights
    corresponding stations on the map via a shared data source.

    Returns:
        Bokeh column layout containing map and CDF with linked selections
    """
    # Collect backlog data
    df = collect_backlog_data()

    if df is None or df.empty:
        from bokeh.models import Div
        return Div(text="<p>No backlog data available.</p>")

    # Sort data once for CDF and add cdf_y column
    df_sorted = df.sort_values('backlog_months').reset_index(drop=True)
    df_sorted['cdf_y'] = (df_sorted.index + 1) / len(df_sorted)

    # Create shared data source with sorted data
    shared_source = ColumnDataSource(df_sorted)

    # Create both plots using the same sorted data
    map_plot = plot_backlog_map(df_sorted, shared_source)
    cdf_plot = plot_backlog_cdf(df_sorted, shared_source)

    # Return linked plots
    return column(map_plot, cdf_plot)


